In [2]:
# CREATING A NUMPY ARRAY
mylist = [1,2,3,4]

In [3]:
# importing numpy package
import numpy as np

In [6]:
# creating a numpy array from a list
numpy1 = np.array(mylist)

In [7]:
numpy1

array([1, 2, 3, 4])

In [19]:
# create an numpy array within a given range
# we need to pass the start , stop and step values
arr1=np.arange(1,20,2)
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
# create an array of zeros
# need to pass in the shape of the array
arr2= np.zeros((8,5))
# here we have given (8,5) and the function outputs eight rows and five columns of zeroes
# the point following a zero is because it is creating a float
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
# we can create an array of ones by invoking the np.ones function 
arr3= np.ones((3,10))
# we have passed a shape of (3,10) as an argument and hence we get an output of three rows and ten columns 
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
# generating random numbers/ numpy has a module called random that has several built in functions
# random seed is used to ensure the results are reproducible
#random,randint would generate random numbers. its arguments are low- lowest number , high - highest number ,size - number of
# random values to be generated
np.random.seed(101)
arr4= np.random.randint(10,100,10)
arr4

array([21, 91, 80, 73, 97, 85, 19, 87, 50, 14])

In [26]:
# numpy fucntion to find a maximum value in an given array
np.max(arr4)

97

In [27]:
# numpy function to locate the index of the maximum value in an given array
np.argmax(arr4)

4

In [ ]:
# in the above function np.argmax the maximum value is at the index 4 in the array - arr4
# hence the output is four

In [28]:
# numpy function to locate the minimum value in an array
# to get the value use np.min()

np.min(arr4)

14

In [29]:
# to get the location of the minimum value use - np.argmin()
np.argmin(arr4)

9

In [30]:
# numpy function to calculate the average value in a given array use np.mean()
np.mean(arr4)

61.7

In [39]:
# reshaping an array
# create an array
arr5 = np.array([22,33,44,55,66,77,88,99,11,22,])
arr5


array([22, 33, 44, 55, 66, 77, 88, 99, 11, 22])

In [40]:
arr5.shape

(10,)

In [42]:
# reshaping the array to (2,5)
# make sure the array has sufficient elements for reshaping to new dimension
arr5.reshape((2,5))

array([[22, 33, 44, 55, 66],
       [77, 88, 99, 11, 22]])

In [46]:
# slicing and indexing in numpy
# create an array and reshape
mat1 = np.arange(0,100).reshape((10,10))
mat1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [47]:
# indexing the value located on row 5 and column 5
mat1[5,5]

55

In [55]:
# extract all the elements in the row three
mat1[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [61]:
# extract all the elements in the fourth column
mat1[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [62]:
# the above array can be reshaped
mat1[:,4].reshape((10,1))

array([[ 4],
       [14],
       [24],
       [34],
       [44],
       [54],
       [64],
       [74],
       [84],
       [94]])

In [63]:
# to get first three rows and first three columns from the matrix
mat1[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [65]:
# reassign a value zero to first four rows and first five columns
mat1[0:4,0:5]=0
mat1

array([[ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0,  0, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0,  0, 25, 26, 27, 28, 29],
       [ 0,  0,  0,  0,  0, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
# create a copy of the matrix
mat2= mat1.copy()

In [69]:
mat2

array([[ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0,  0, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0,  0, 25, 26, 27, 28, 29],
       [ 0,  0,  0,  0,  0, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [71]:
# reassign 999 to first four rows
mat1[0:5,:]=999

In [72]:
mat1

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])